### PR TITLE
Add postprocessing collation helper, minor prod/util edits

### PR DESCRIPTION
**Pull request by dylanhmorris**
- Create script `postprocess_forecast_batches.py` to automate plot collation, hubverse table creation, etc
- Fix some import bugs in `utils.py`
- Make `setup_prod_job.py` default to a job with `COVID-19` and `Influenza` as the `diseases`
- Add test of postprocessing via `postprocess_forecast_batches.py` to the end to end test, and make the end to end test try multiple locations x multiple diseases, including US national forecasts.

### CODE REVIEW

**Comment by damonbayer** [comment]
Closes https://github.com/CDCgov/pyrenew-hew/issues/163 ?

**Comment by dylanhmorris** [comment]
> Closes https://github.com/CDCgov/pyrenew-hew/issues/163 ?

Prerequisite but as written doesn't close because it's just a local helper for now and I didn't yet do anything with task dependencies for an azure prod job.

**Comment by dylanhmorris** [comment]
@damonbayer ready for review.

**Review by damonbayer — COMMENTED** [review]
Do you think it would be possible to do a postprocess test in CI in this PR? I think that would put us in a really good position for making sure all the PyRenew-HE changes continue to work.

**Review by damonbayer — CHANGES_REQUESTED** [review]
Assuming this is still WIP, but formally requesting changes to address the CI failure.

**Comment by dylanhmorris** [comment]
All CI now passes; ready for re-review @damonbayer (or @sbidari since @damonbayer is out).

**Review by sbidari — APPROVED** [review]
Not a very thorough review but it looks mostly good to me!

**Pull request merged**
