### PR TITLE
issue 116: Generate test posterior samples

### LINKED ISSUE #116: Generate test posterior samples
Sub-task of #105 . This task involves generating test posterior distributions in order to run tests against.

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR closes #116.

This is a simple PR that tidies up the local fit loop utility, and creates a test directory which can be aimed at with `loop_fit.sh`. `.pickle` files are ignored so a test run with unit tests should start with this step.

## Run fake posterior generation

```bash
% bash ./iteration_helpers/loop_fit.sh ./tests/run_test_inference
```

from `/pipelines`.

This will be part of planned test runs.

### CODE REVIEW

**Comment by damonbayer** [comment]
Can we nudge this PR toward https://github.com/CDCgov/pyrenew-hew/issues/57 ? I think we could start to put together tests not in the `nssp_demo` directory?

**Comment by SamuelBrand1** [comment]
> Can we nudge this PR toward #57 ? I think we could start by putting tests not in the `nssp_demo` directory?

I'd rather not guess what structure we want. Happy to hold this until we resolve #57 .

**Comment by SamuelBrand1** [comment]
This works with the new directory structure now.

**Comment by SamuelBrand1** [comment]
updated test folder `priors.py` to track changes in code base.

**Comment by SamuelBrand1** [comment]
Closed as superseded by #148

**Pull request closed without merging**
