### PR TITLE
Draft: Create test pipeline CI - do not merge

### PR DESCRIPTION
**Pull request by SamuelBrand1**
Testing out a CI which installs pyrenew-hew and hewr before running the test pipeline to address #155

### CODE REVIEW

**Comment by SamuelBrand1** [comment]
This errors with:

> Failed to clone https://github.com/cdcent/cfa-stf-azuretools, check your git configuration and permissions for this repository.
Error: Process completed with exit code 1.

@gvegayon Any idea for setting up our runner permission for installing a package from cdcent?

**Comment by damonbayer** [comment]
@SamuelBrand1 This looks like a decent solution: https://stackoverflow.com/questions/57612428/cloning-private-github-repository-within-organisation-in-actions/70283191#70283191

However, I know @dylanhmorris has been wanting to get https://github.com/cdcent/cfa-stf-azuretools [migrated to CDCgov](https://github.com/cdcent/cfa-predict-github-repos-meta/issues/33), but it has not yet been approved. Perhaps our need here could motivate progress on that front.

**Comment by gvegayon** [comment]
I would aim for the healthier alternative: make the repo open. Plan B would be to set up a token (with fine-grained permissions and a short lifespan) to pass to `actions/checkout`.

**Comment by SamuelBrand1** [comment]
> I would aim for the healthier alternative: make the repo open. Plan B would be to set up a token (with fine-grained permissions and a short lifespan) to pass to `actions/checkout`.

100% agree with first sentence. Second sentence encapsulates my concerns here!

**Comment by SamuelBrand1** [comment]
> @SamuelBrand1 This looks like a decent solution: [stackoverflow.com/questions/57612428/cloning-private-github-repository-within-organisation-in-actions/70283191#70283191](https://stackoverflow.com/questions/57612428/cloning-private-github-repository-within-organisation-in-actions/70283191#70283191)
> 
> However, I know @dylanhmorris has been wanting to get cdcent/cfa-stf-azuretools [migrated to CDCgov](https://github.com/cdcent/cfa-predict-github-repos-meta/issues/33), but it has not yet been approved. Perhaps our need here could motivate progress on that front.

I think we should wait for azuretools to become open rather than doing a hack or (from my pov) poorly understood token access with potential security implications.

**Comment by damonbayer** [comment]
@SamuelBrand1 This is unblocked. https://github.com/cdcgov/cfa-azuretools

**Comment by SamuelBrand1** [comment]
This now "works" in the sense that the runner installs the relevant background deps (py and R), and starts the test pipeline. This workflow will now fail if any of the test pipeline steps fail.

However, other changes seem to have broken the actual test pipeline process.

We want something like this for #52 #126 #155 so it would be good to get the test pipeline fixed, then we can capture breaking changes in the future.

**Comment by damonbayer** [comment]
> Is it worth fixing the test pipeline @damonbayer ?

I think it would be a quick fix to get your `pipelines/tests/test_run.sh` working. But, in the spirit of DRY, we should probably be sharing more code between the production run and the test run. If we tackle  https://github.com/CDCgov/pyrenew-hew/issues/149, I think we could just run a `main` from https://github.com/CDCgov/pyrenew-hew/blob/main/pipelines/forecast_state.py in our testing.

**Comment by SamuelBrand1** [comment]
Closing this due to #216

**Pull request closed without merging**
