### PR TITLE
Issue 53: Model for prediction non-target pathogens

### LINKED ISSUE #53: A model to generate $N(t)$.
This issue is aimed at selecting a method for forecasting the _independent_ part of the denominator of the fraction:

```math
P(t) = {X(t) \over X(t) + N(t)}.
```

Where $X(t)$ is a target pathogen which is modelled using a sophisticated method e.g. `pyrenew-hew`, and $N(t)$ are the remainder of the numerator.

This approach assumes that independence of $X(t)$ is $N(t)$ is reasonable; for example when $N(t)$ is a mix of some other respiratory virus incidence but pre-dominantly non-infectious disease causes.

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR closes #53 .

This PR adds two R functions in the folder `countpredr/R` along with associated unit tests. The added functionality:

- `generate_example_data`: This generates rough estimates of weekly ED visit counts based on publicly available data (see `README` and docstrings.
- `forecast_counts`: This generates forecasts of $N(t)$ using the `fable` package.

This PR also adds an example usage note rendered to `gfm` at `countpredr/README.md`.

## Forecast model

The forecast model is an ensemble of an ETS and a SARIMA model fitted on `log(count)` data (see `countpredr/README.md`). This is not a tuneable option, but rather an (IMO) robust forecaster for short term prediction of the non-target pathogen(s)/causes that we can use whilst focusing on forecasting the target pathogen.

Note that discrete degrees of freedom in model selection are auto-tuned over the default selection space by `fable::model`. I have changed the defaults for the ETS trend model so that a multiplicative option is part of the model selection space (`trend(method = c("N", "M", "A"))`).

## Context

This is part of resolving #47 by creating a forecast model for _non-target_ pathogens. The obvious next step is to add this to predictive modelling workflow, a simple example of doing this by joining to predictive samples is given in the README.

### CODE REVIEW

**Review by damonbayer — COMMENTED** [review]
Thanks @SamuelBrand1! This looks really nice. Before I approve/merge I need to think a bit more about how we organize the various demos that are going into this project.

**Comment by SamuelBrand1** [comment]
> Thanks @SamuelBrand1! This looks really nice. Before I approve/merge I need to think a bit more about how we organize the various demos that are going into this project.

I don't think you have an issue for this? 

I think this would be more effective with an issue laying out what your goals are, then we can add specifications to #47 .

**Comment by damonbayer** [comment]
@SamuelBrand1 I think I will likely close this PR in favor of https://github.com/CDCgov/pyrenew-hew/pull/68

**Comment by SamuelBrand1** [comment]
> @SamuelBrand1 I think I will likely close this PR in favor of #68

I think it might be worth merging this too. This could facilitate using the `fable` utilities as part of `scoringutilhelpers` (e.g. baseline forecaster).

**Pull request closed without merging**
